export const CURSOR_MOVE_EPSILON = 0.0005;
export const TRIGGER_DRAG_THRESHOLD = 0.015;
export const TRIGGER_CLICK_CANCEL_THRESHOLD = 0.03;
export const TRIGGER_SCROLL_MULTIPLIER = 0.5;
export const TRIGGER_SCROLL_MAX = 140;
