/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * VRオーバーレイを管理するN-APIラッパー。
 *
 * 注意: `!Send` / `!Sync` のため同一スレッドでのみ使用してください。
 */
export declare class OverlayManager {
  constructor()
  getControllerIds(): Array<number>
  getControllerPose(index: number): Array<number>
  getControllerState(controllerIndex: number): ControllerState
  initInput(manifestAbsPath: string): void
  pollToggleClicked(): boolean
  openBindingUi(appKey: string, showOnDesktop: boolean): void
  getCurrentBindings(): CurrentBindings
  createOverlay(key: string, name: string): number
  destroyOverlay(handle: number): void
  showOverlay(handle: number): void
  hideOverlay(handle: number): void
  toggleOverlay(handle: number): void
  setOverlayWidth(handle: number, widthMeters: number): void
  setOverlayTextureBounds(handle: number, uMin: number, vMin: number, uMax: number, vMax: number): void
  computeOverlayIntersection(handle: number, source: Array<number>, direction: Array<number>): IntersectionResult | null
  setOverlayFromFile(handle: number, filePath: string): void
  setOverlayRaw(handle: number, buffer: Buffer, width: number, height: number): void
  setOverlayTexturesD3D11(frontHandle: number, backHandle: number, buffer: Buffer, width: number, height: number): void
  setOverlayTransformHmd(handle: number, distance: number): void
  getOverlayTransformAbsolute(handle: number): Array<number>
  setOverlayTransformAbsolute(handle: number, matrix: Array<number>): void
  getOverlayTransformType(handle: number): number
  getOverlayTransformRelative(handle: number): OverlayRelativeTransform
}

export interface ControllerState {
  triggerPressed: boolean
  triggerValue: number
  gripPressed: boolean
  touchpadPressed: boolean
  touchpadX: number
  touchpadY: number
  joystickPressed: boolean
  joystickX: number
  joystickY: number
}

export interface CurrentBindings {
  initialized: boolean
  toggleOverlay: Array<string>
  triggerBindings: Array<string>
  gripBindings: Array<string>
  triggerBound: boolean
  gripBound: boolean
}

export interface IntersectionResult {
  x: number
  y: number
  z: number
  u: number
  v: number
  distance: number
}

export interface OverlayRelativeTransform {
  trackedDeviceIndex: number
  transform: Array<number>
}
